version: '3'
services:
  robot-runner:
    container_name: robot-runner
    build: .
#    image: ppodgorsek/robot-framework:latest
    volumes:
      - ./tests:/tests
      - ./schema:/schema
      - ./resource:/resource
      - ./keyword:/keyword
      - ./config:/config
      - ./results:/results
    environment:
      PYTHONWARNINGS: "ignore:Unverified HTTPS request"
